[package]
name = "chain"
version = "0.1.0"
authors = ["Odaka Ui <31593320+odakaui@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.24"
dirs = "3.0"
chrono = "0.4.0"
